Initial
karolisMtb/CareerPlatform pull request #1
Opened 2023-10-17 17:59 UTC by karolisMtb

For review

2023-10-18 10:47 UTC, dora1212 requested changes
Vienas bendras komentaras, kad nesuprantu, kam reikia Shared projekto. Tuos objektus gi gali įdėti į kurį nors projektą, vieną iš trijų layerių, ir tada per project reference jie bus pasiekiami ir kituose projektuose.

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Program.cs
> +
Iškomentuotų šiukšlių nereiktų komitinti. Jas gali pasilikti lokaliai.

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +    //[Route("api/[controller]")]
Ištrinti

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +                return BadRequest(e.Message);
Čia labiau tiktų error kodas 409 (conflict) - pasiskaityk.

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +                return BadRequest(e.Message);
Server side error kodas yra 500, ne 400.

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +        public async Task<IActionResult> SignUp([FromForm] UserSignUpDto userSignUpDto)
Tavo endpointų pavadinimai neatitinka RESTful standartų. Endpointas turėtų būti pavadintas resurso, ne action pavadinimu. "Authentication" butu tinkamesnis pavadinimas logino endpointui, kitus susigalvok pats, chat gpt padės.

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +            finally
Nėra priežasties turėti finally, nėra resursų, kuriuos reikia release'inti.

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +                return BadRequest(e.Message);
Blogas error kodas, turėtų būti 401 - unauthorized.

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +                return BadRequest(e.Message);
Čia irgi 401

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +            //try
vėl šiukšlių kalnai, negalima tokio šiukšlyno komitinti

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +        [ProducesResponseType(StatusCodes.Status200OK)]
Response type'us irgi reikia taisyti, nebeatitinka

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.BusinessLogic/Services/UserService.cs
> +        public async Task<string> AuthenticateUserAsync(UserLoginDto loginDto)
Nelabai suprantu, kam du metodai AuthenticateUserAsync ir AuthenticateAsync. Kodėl neturėti vieno? Šitas metodas taip ar taip nieko nedaro.

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.BusinessLogic/Services/UserService.cs
> +        private async Task<string> GenerateTokenAsync(User currentUser)
Šitą metodą gali padaryti sinchroniniu, jis taip ar taip eina sinchroniškai

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.BusinessLogic/Services/UserService.cs
> +            if (userExists == true)
Užtenka if(userExists)

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.BusinessLogic/Services/UserService.cs
> +            if (userDto.email == null || userDto.userName == null || userDto.password == null)
Gal validation iškelk į endpointą? Jei vienas iš šitų null, kokio velnio eit iki šitos eilutės ir degint kurą? Be to, tikrink su fluent validatorium.

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.BusinessLogic/Services/UserService.cs
> +        private async Task<User> CreateNewUserAsync(UserSignUpDto userDto)
Metodą daryti sinchroniniu arba pridėti await

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.BusinessLogic/Services/UserService.cs
> +            if (userId == Guid.Empty)
Validation'as į enpointą

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.BusinessLogic/Services/UserService.cs
> +            if (userId == Guid.Empty)
Validation'as į enpointą

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.BusinessLogic/Services/UserService.cs
> +    public class UserService : IUserService
Išskirstyčiau į authentication service ir user service

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.DataAccess/UnitOfWork/UnitOfWork.cs
> +        public async Task SaveChangesAsyn()
Typo

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.DataAccess/Repositories/UserRepository.cs
> +            User user = await _platformDbContext.Users.Where(u => u.Id == userId).FirstAsync();
Pakeisk į FirstOrDefaultAsync, nes jei bus null, mes exception'ą iškart.

2023-10-18 10:47 UTC, dora1212 commented on CareerPlatform/CareerPlatform.DataAccess/Repositories/UserRepository.cs
> +            User currentUser = await _platformDbContext.Users.Where(x => x.UserName == credential || x.Email == credential).FirstAsync();
Čia irgi FirstOrDefaultAsync dėl tos pačios priežasties

2023-10-18 13:54 UTC, karolisMtb commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +                return BadRequest(e.Message);
zinau. Nebuvau cia padares klaidos. 200, 400, 500, OK, Client side, Server side

2023-10-18 13:54 UTC, karolisMtb commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +            finally
palikau finally, kad issiaiskinciau kam ir kada jis naudojamas. Aciu

2023-10-18 14:59 UTC, karolisMtb commented on CareerPlatform/CareerPlatform.BusinessLogic/Services/UserService.cs
> +        public async Task<string> AuthenticateUserAsync(UserLoginDto loginDto)
Pataisyta

2023-10-24 21:10 UTC, karolisMtb commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +        public async Task<IActionResult> SignUp([FromForm] UserSignUpDto userSignUpDto)
pataisyta

2023-10-24 21:15 UTC, karolisMtb commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +        [ProducesResponseType(StatusCodes.Status200OK)]
Sito nelabai supratau, nes viskas lyg ir atitinka. Nebent tu turi omeny atributus

2023-10-24 21:18 UTC, karolisMtb commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +                return BadRequest(e.Message);
sita reikia prachekinti kartu. Prieisi

2023-10-24 21:20 UTC, karolisMtb commented on CareerPlatform/CareerPlatform/Controllers/UserController.cs
> +            //try
done

2023-11-07 10:26 UTC, dora1212 reviewed
Dar susitvarkyk gitignore, kad includintu .vs folderi.

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +    [Route("api/authenticate")]
Šitas endpointas ir yra authenticate, jei paliksi [controller]

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +                return Unauthorized(); //tikrai unauthorized turi buti?
Tinka, dar tiktu 404 Not found

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +                return BadRequest("Server side error");
Bad request (400) nera server side error(500). Paklausk chat gpt kuo sitie du skiriasi. Pagrindini ju skirtumas yra tas, kad vienas yra user side, kitas server side.

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +        private readonly RoleManager<IdentityRole> _roleManager;
Istrink, nenaudojamas

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +        public async Task<IActionResult> Login([FromBody] LoginModel model)
Sitas metodui siulau mazdaug tokia kodo struktura (pateikiu pseudo koda):

if(authenticationService.FindByName(credentials) && authenticationService.CheckPassword(credentials))
{
   token = AuthenticationService.GetToken();
   return OK(token);
}
return Unauthorized();

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +                var userByName = await _userManager.FindByNameAsync(model.Username);
Kodel tikrini pagal name? Name nera unikalus. Reiktu tikrinti pagal viena identifikatoriu, geriausia turbut pagal emaila

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +                IdentityUser user = new()
Visas userio sukurimas, nuo 129 iki 145 eilutes keliauja i servisa

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +                if (user is not null)
Ar man gerai matosi, kad sitas kodas issiuncia Accepted net tada, kai useris yra null?

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +        public async Task<IActionResult> ResetPassword(string email, string token)
Sitas endpointas strukturiskai panasesnis i toki, koks turetu buti.

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +                    return BadRequest(result.Errors);
O butinas sitas? Ka resetPasswordAsync pats neismeta exceptiono, jei kazkas buna?

2023-11-07 10:26 UTC, dora1212 commented on CareerPlatform/CareerPlatform/Controllers/AuthenticateController.cs
> +                if (!result.Succeeded)
Sitas neveiks, nes jei !result.Succeeded servisas ismes TargetInvocationException ir nedaeis iki sito kodo

2023-12-27 08:41 UTC, dora1212 approved these changes

2023-12-27 08:50 UTC, merged